<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite errors="1" failures="0" name="unittest.suite._ErrorHolder-20190315210856" skipped="0" tests="1" time="0.000" timestamp="0001-01-01T00:00:00">
		<testcase classname="setUpClass (comments.tests.test_api" name="APITests)" time="0.000" timestamp="0001-01-01T00:00:00">
			<error message="division by zero" type="ZeroDivisionError">
<![CDATA[Traceback (most recent call last):
  File "/home/user/Projects/myapp/comments/tests/test_api.py", line 21, in setUpClass
    1/0
ZeroDivisionError: division by zero
]]>			</error>
		</testcase>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testsuite>
</testsuites>
