<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite errors="6" failures="0" name="comments.tests.test_api.APITests-20190315210928" skipped="0" tests="6" time="0.001" timestamp="2019-03-15T21:09:28">
		<testcase classname="comments.tests.test_api.APITests" name="test_api" time="0.000" timestamp="2019-03-15T21:09:28">
			<error message="division by zero" type="ZeroDivisionError">
<![CDATA[Traceback (most recent call last):
  File "/home/user/Projects/myapp/comments/tests/test_api.py", line 20, in setUp
    1/0
ZeroDivisionError: division by zero
]]>			</error>
		</testcase>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testsuite>
</testsuites>
