FAILED. Ran 12 tests in 0.033s (errors=0, failures=12, skipped=0)
/home/user/Projects/tests/test_nodes.py:16: setUp : TypeError: __init__() got an unexpected keyword argument 'buffer' : self.node = self.given_node()
/home/user/Projects/buffers.py:27:`-  create_leaf :  : **kwargs,
